In [6]:
import requests
import pandas as pd

In [316]:
# # Mengambil data JSON dari API untuk daftar provinsi
# responses_states = requests.get('http://api.airvisual.com/v2/states?country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()
# provinsi = [state['state'] for state in responses_states['data']]
# provinsi

# requests.get('http://api.airvisual.com/v2/cities?&state=Yogyakarta&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

In [5]:
from datetime import datetime
import pytz

### Jakarta

In [13]:
jakarta = requests.get('http://api.airvisual.com/v2/city?city=Jakarta&state=Jakarta&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
# negara = jakarta['data']['country']
provinsi = jakarta['data']['state']
kota = jakarta['data']['city']
koordinat = jakarta['data']['location']['coordinates']
tanggal = jakarta['data']['current']['pollution']['ts']
aqius = jakarta['data']['current']['pollution']['aqius']
mainus = jakarta['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')

# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = tanggal.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}

#Menampilkan DataFrame
df_jakarta = pd.DataFrame.from_dict(data_dict)

df_jakarta['tanggal'] = pd.to_datetime(df_jakarta['tanggal'])
# df_jakarta['tanggal'] = df_jakarta['tanggal'].dt.strftime('%Y-%m-%d %H:%M')
df_jakarta

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-12-02,Jakarta,Jakarta,"[106.79324, -6.236704]",52,p2

In [14]:
df_jakarta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tanggal         1 non-null      datetime64[ns]
 1   provinsi        1 non-null      object
 2   kota            1 non-null      object
 3   koordinat       1 non-null      object
 4   kualitas_udara  1 non-null      int64
 5   polutan_utama   1 non-null      object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 176.0+ bytes

### Aceh

In [278]:
# data_aceh = requests.get('http://api.airvisual.com/v2/cities?&state=Aceh&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# data_kota = []
# for i in range(len(data_aceh)):
#     kota = data_aceh['data'][i]['city']
#     kota = kota.replace(' ','%20')
#     data_kota.append(kota)

aceh = requests.get('http://api.airvisual.com/v2/city?city=Banda%20Aceh&state=Aceh&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = aceh['data']['state']
kota = aceh['data']['city']
koordinat = aceh['data']['location']['coordinates']
tanggal = aceh['data']['current']['pollution']['ts']
aqius = aceh['data']['current']['pollution']['aqius']
mainus = aceh['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_aceh = pd.DataFrame.from_dict(data_dict)
# df_aceh['tanggal'] = pd.to_datetime(df_aceh['tanggal'], errors='coerce')
# df_aceh['tanggal'] = df_aceh['tanggal'].dt.strftime('%Y-%m-%d %H:%M')
df_aceh

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Aceh,Banda Aceh,"[95.33333, 5.54167]",45,p2

### Bali - Depasar

In [281]:
bali = requests.get('http://api.airvisual.com/v2/city?city=Denpasar&state=Bali&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = bali['data']['state']
kota = bali['data']['city']
koordinat = bali['data']['location']['coordinates']
tanggal = bali['data']['current']['pollution']['ts']
aqius = bali['data']['current']['pollution']['aqius']
mainus = bali['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_bali = pd.DataFrame.from_dict(data_dict)
df_bali

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Bali,Denpasar,"[115.19754, -8.663225]",48,p2

### Banten - Tangsel

In [314]:
tangsel = requests.get('http://api.airvisual.com/v2/city?city=South%20Tangerang&state=Banten&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = tangsel['data']['state']
kota = tangsel['data']['city']
koordinat = tangsel['data']['location']['coordinates']
tanggal = tangsel['data']['current']['pollution']['ts']
aqius = tangsel['data']['current']['pollution']['aqius']
mainus = tangsel['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_tangsel = pd.DataFrame.from_dict(data_dict)
df_tangsel

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Banten,South Tangerang,"[106.71789, -6.28862]",70,p2

### Jawa Tengah - Semarang

In [295]:
semarang = requests.get('http://api.airvisual.com/v2/city?city=Semarang&state=Central%20Java&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = semarang['data']['state']
kota = semarang['data']['city']
koordinat = semarang['data']['location']['coordinates']
tanggal = semarang['data']['current']['pollution']['ts']
aqius = semarang['data']['current']['pollution']['aqius']
mainus = semarang['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_semarang = pd.DataFrame.from_dict(data_dict)
df_semarang

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Central Java,Semarang,"[110.42083, -6.99306]",77,p2

### Jawa Timur - Surabaya

In [296]:
surabaya = requests.get('http://api.airvisual.com/v2/city?city=Surabaya&state=East%20Java&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = surabaya['data']['state']
kota = surabaya['data']['city']
koordinat = surabaya['data']['location']['coordinates']
tanggal = surabaya['data']['current']['pollution']['ts']
aqius = surabaya['data']['current']['pollution']['aqius']
mainus = surabaya['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_surabaya = pd.DataFrame.from_dict(data_dict)
df_surabaya

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,East Java,Surabaya,"[112.7946058, -7.2800904]",120,p2

### Jawa Barat - Bandung

In [297]:
bandung = requests.get('http://api.airvisual.com/v2/city?city=Bandung&state=West%20Java&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = bandung['data']['state']
kota = bandung['data']['city']
koordinat = bandung['data']['location']['coordinates']
tanggal = bandung['data']['current']['pollution']['ts']
aqius = bandung['data']['current']['pollution']['aqius']
mainus = bandung['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_bandung = pd.DataFrame.from_dict(data_dict)
df_bandung

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,West Java,Bandung,"[107.60694, -6.92222]",79,p2

### Kalimantan Tengah - Palangkaraya

In [299]:
palangkaraya = requests.get('http://api.airvisual.com/v2/city?city=Palangkaraya&state=Central%20Kalimantan&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = palangkaraya['data']['state']
kota = palangkaraya['data']['city']
koordinat = palangkaraya['data']['location']['coordinates']
tanggal = palangkaraya['data']['current']['pollution']['ts']
aqius = palangkaraya['data']['current']['pollution']['aqius']
mainus = palangkaraya['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_palangkaraya = pd.DataFrame.from_dict(data_dict)
df_palangkaraya

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Central Kalimantan,Palangkaraya,"[113.913977, -2.2161048]",14,p2

### Jambi - Muara Sabak

In [308]:
muara_sabak = requests.get('http://api.airvisual.com/v2/city?city=Muara%20Sabak&state=Jambi&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = muara_sabak['data']['state']
kota = muara_sabak['data']['city']
koordinat = muara_sabak['data']['location']['coordinates']
tanggal = muara_sabak['data']['current']['pollution']['ts']
aqius = muara_sabak['data']['current']['pollution']['aqius']
mainus = muara_sabak['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_muara_sabak = pd.DataFrame.from_dict(data_dict)
df_muara_sabak

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Jambi,Muara Sabak,"[103.84987, -1.13612]",58,p2

### Yogyakarta - Sleman

In [310]:
sleman = requests.get('http://api.airvisual.com/v2/city?city=Sleman&state=Yogyakarta&country=Indonesia&key=ff561aa8-460f-448b-abd2-005fb3496f23').json()

# Mengambil kolom-kolom tertentu dari data JSON
provinsi = sleman['data']['state']
kota = sleman['data']['city']
koordinat = sleman['data']['location']['coordinates']
tanggal = sleman['data']['current']['pollution']['ts']
aqius = sleman['data']['current']['pollution']['aqius']
mainus = sleman['data']['current']['pollution']['mainus']


tanggal = datetime.strptime(tanggal, '%Y-%m-%dT%H:%M:%S.%fz')
# Mengonversi ke zona waktu Jakarta (WIB)
tanggal = tanggal.astimezone(pytz.timezone('Asia/Jakarta'))
tanggal = datetime_object.date()

# Membuat Pandas DataFrame
data_dict = {
    'tanggal': [tanggal],
    'provinsi': [provinsi],
    'kota': [kota],
    # 'country': [country],
    'koordinat': [koordinat],
    'kualitas_udara':[aqius],
    'polutan_utama':[mainus]
}


df_sleman = pd.DataFrame.from_dict(data_dict)
df_sleman

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Yogyakarta,Sleman,"[110.35556, -7.71556]",63,p2

### Concat Data

In [315]:
df = pd.concat([df_jakarta,df_aceh,df_bali,df_bandung,df_tangsel,df_muara_sabak,df_palangkaraya,df_semarang,df_sleman,df_surabaya])
df

,tanggal,provinsi,kota,koordinat,kualitas_udara,polutan_utama
0,2023-11-27,Jakarta,Jakarta,"[106.79324, -6.236704]",65,p2
0,2023-11-27,Aceh,Banda Aceh,"[95.33333, 5.54167]",45,p2
0,2023-11-27,Bali,Denpasar,"[115.19754, -8.663225]",48,p2
0,2023-11-27,West Java,Bandung,"[107.60694, -6.92222]",79,p2
0,2023-11-27,Banten,South Tangerang,"[106.71789, -6.28862]",70,p2
0,2023-11-27,Jambi,Muara Sabak,"[103.84987, -1.13612]",58,p2
0,2023-11-27,Central Kalimantan,Palangkaraya,"[113.913977, -2.2161048]",14,p2
0,2023-11-27,Central Java,Semarang,"[110.42083, -6.99306]",77,p2
0,2023-11-27,Yogyakarta,Sleman,"[110.35556, -7.71556]",63,p2
0,2023-11-27,East Java,Surabaya,"[112.7946058, -7.2800904]",120,p2